language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run python src/generator/python/main.py --protobufs-root src/generator/resources --generated-root generated/models -v
  - pipenv run python setup.py test
