name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install

    - name: Generate
      run: |
        pipenv run python src/generator/python/main.py --protobufs-root src/generator/resources --generated-root generated/models -v

    - name: Test
      run: |
        pipenv run python setup.py test
